import { Tour } from "./types";

export const toursData: Tour[] = [
  {
    id: "tour-medina",
    slug: "marrakesh-medina-tour",
    title: "Marrakesh Medina, Souks & Heritage Experience",
    subtitle: "Historic Medina, vibrant souks, and iconic cultural landmarks with Zaky",
    cls: "t1",
    icon: "gate",
    duration: "3–4 hours",
    groupType: "1–10 guests | Private Tour",
    languages: "English, French, Arabic",
    price: "700 MAD",
    priceNote: "700 MAD per private group, up to 10 guests",
    description:
      "Discover the heart of Marrakesh on a private walking tour through the historic Medina, vibrant souks, and iconic cultural landmarks. Explore Ben Youssef Madrasa, The Secret Garden, and Jemaa el-Fna while enjoying fascinating local stories, history, and cultural insights from your private guide.",
    fullDescription: [
      "Discover the heart of Marrakesh on a private walking tour through the historic Medina, vibrant souks, and iconic cultural landmarks. Explore Ben Youssef Madrasa, The Secret Garden, and Jemaa el-Fna while enjoying fascinating local stories, history, and cultural insights from your private guide.",
      "The Medina of Marrakesh is a vibrant, centuries-old maze where history breathes through every stone, archway, and carved cedar beam. With Zaky as your private local guide, you will bypass the confusing tourist detours and enter genuine local neighborhoods.",
      "Your private walk moves entirely at your comfort and pace. You will discover sacred foundation architecture, traditional artisan souks, and legendary landmarks while hearing the oral histories passed down through generations.",
    ],
    highlights: [
      "Ben Youssef Madrasa",
      "The Secret Garden",
      "Marrakesh Medina",
      "Traditional Souks",
      "Jemaa el-Fna Square",
    ],
    gallery: [
      {
        src: "/images/medina.jpg",
        alt: "Sunlit alleyway in the historic Marrakesh Medina",
        caption: "Ancient ochre alleyways and carved wooden doorways of the Medina.",
      },
      {
        src: "/images/hero.jpg",
        alt: "Zaky in a traditional riad courtyard",
        caption: "Zaky guiding guests through historic architectural landmarks.",
      },
      {
        src: "/images/souks.jpg",
        alt: "Vibrant lantern and carpet souks",
        caption: "Encountering the artisan quarters tucked inside the walled city.",
      },
      {
        src: "/images/bahia.jpg",
        alt: "Traditional courtyard architecture",
        caption: "Tranquil palace courtyards hidden behind unassuming wooden gates.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Ben Youssef Madrasa",
        duration: "45 mins",
        description: "Explore the renowned 14th-century Islamic college, admired for its exquisite carved cedarwood, stuccowork, and colorful zellij mosaics.",
        lat: 31.6320,
        lng: -7.9868,
      },
      {
        stopNumber: 2,
        name: "The Secret Garden (Le Jardin Secret)",
        duration: "45 mins",
        description: "Discover an oasis of tranquility in the heart of the Medina, restored with traditional Islamic and exotic botanical gardens and ancient khettara irrigation.",
        lat: 31.6300,
        lng: -7.9899,
      },
      {
        stopNumber: 3,
        name: "Marrakesh Medina Historic Alleys & Fondouks",
        duration: "45 mins",
        description: "Stroll through quiet residential lanes, historic merchant caravanserais, and communal neighborhood bread bakeries.",
        lat: 31.6294,
        lng: -7.9898,
      },
      {
        stopNumber: 4,
        name: "Traditional Souks & Craft Quarters",
        duration: "45 mins",
        description: "Navigate authentic artisan souks where master craftsmen shape brass lanterns, weave textiles, and display colorful spices.",
        lat: 31.6288,
        lng: -7.9860,
      },
      {
        stopNumber: 5,
        name: "Jemaa el-Fna Square",
        duration: "45 mins",
        description: "Conclude at the famed UNESCO-recognized square, immersed in the vibrant energy of storytellers, musicians, and traditional heritage.",
        lat: 31.6258,
        lng: -7.9891,
      },
    ],
    mapCenter: { lat: 31.6295, lng: -7.9880, zoom: 15 },
    included: [
      "Private official tour guide",
      "Personalized walking tour",
      "Local stories, history and cultural insights",
      "Assistance and local recommendations",
    ],
    notIncluded: [
      "Entrance fees",
      "Food and drinks",
      "Personal purchases",
      "Transportation",
    ],
  },
  {
    id: "tour-souks",
    slug: "souks-local-markets",
    title: "Marrakesh Souks & Local Markets Experience",
    subtitle: "Step beyond the main tourist routes into vibrant artisan workshops and markets",
    cls: "t2",
    icon: "basket",
    duration: "Approximately 3 hours",
    groupType: "Up to 10 guests | Private Group",
    languages: "English, French, Arabic",
    price: "700 MAD",
    priceNote: "700 MAD per private group — up to 10 guests",
    description:
      "Explore the authentic side of Marrakesh through vibrant local markets, traditional souks, and artisan workshops. Discover Moroccan flavors, crafts, and everyday traditions while experiencing the hidden streets and lively atmosphere of the Medina with a private local guide.",
    fullDescription: [
      "Explore the authentic side of Marrakesh through vibrant local markets, traditional souks, and artisan workshops. Discover Moroccan flavors, crafts, and everyday traditions while experiencing the hidden streets and lively atmosphere of the Medina with a private local guide.",
      "Step beyond the main tourist routes and discover the markets, souks and artisan workshops where Marrakesh comes alive.",
      "Explore the colors, aromas and traditions of the city while learning how local people shop, work and live. From fresh produce and spices to traditional crafts, this experience offers a more authentic perspective of Marrakesh.",
    ],
    highlights: [
      "Local food markets",
      "Traditional neighborhood souks",
      "Spices, olives, fruits and vegetables",
      "Moroccan handicrafts and artisan workshops",
      "Traditional products and local specialties",
      "Hidden streets and authentic corners of the Medina",
      "Everyday life and traditions of Marrakesh",
    ],
    gallery: [
      {
        src: "/images/souks.jpg",
        alt: "Vibrant lantern and carpet souks",
        caption: "Glowing handcrafted brass lamps and hand-knotted Berber carpets.",
      },
      {
        src: "/images/medina.jpg",
        alt: "Medina market alleys",
        caption: "Navigating quiet side souks where master artisans work.",
      },
      {
        src: "/images/bahia.jpg",
        alt: "Carved details in architectural setting",
        caption: "Appreciating centuries-old craft traditions still practiced today.",
      },
      {
        src: "/images/hero.jpg",
        alt: "Zaky with guests in Marrakesh",
        caption: "Zaky explaining artisan traditions with guests.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Local Food & Fresh Produce Markets",
        duration: "35 mins",
        description: "Explore traditional food markets bustling with seasonal fruits, Moroccan olives, fresh herbs, and aromatic vegetables.",
        lat: 31.6315,
        lng: -7.9910,
      },
      {
        stopNumber: 2,
        name: "Traditional Neighborhood Souks",
        duration: "40 mins",
        description: "Venture into neighborhood souks away from the typical tourist trails, observing how locals shop for daily household goods and textiles.",
        lat: 31.6272,
        lng: -7.9880,
      },
      {
        stopNumber: 3,
        name: "Spices & Apothecary Quarter (Rahba Kedima)",
        duration: "35 mins",
        description: "Discover the vibrant scents and colors of ras el hanout, pure saffron, cumin, and Moroccan cosmetic argan oil.",
        lat: 31.6288,
        lng: -7.9860,
      },
      {
        stopNumber: 4,
        name: "Moroccan Handicrafts & Artisan Workshops",
        duration: "40 mins",
        description: "Watch skilled master craftsmen at work in traditional ateliers — from wood carving and leather stitching to brass lamps.",
        lat: 31.6300,
        lng: -7.9870,
      },
      {
        stopNumber: 5,
        name: "Hidden Streets & Daily Medina Traditions",
        duration: "30 mins",
        description: "Wander peaceful hidden residential derbs (alleyways) to appreciate everyday life, neighborhood community ovens, and local heritage.",
        lat: 31.6294,
        lng: -7.9898,
      },
    ],
    mapCenter: { lat: 31.6290, lng: -7.9880, zoom: 16 },
    included: [
      "Private official tour guide",
      "Personalized walking tour",
      "Local insights and recommendations",
      "Introduction to Moroccan craftsmanship and local products",
    ],
    notIncluded: [
      "Food and drinks",
      "Personal purchases",
      "Entrance fees, if applicable",
      "Transportation",
    ],
  },
  {
    id: "tour-historical",
    slug: "historical-marrakesh",
    title: "Marrakesh Historical & Cultural Heritage Tour",
    subtitle: "Discover the history and heritage of the Red City",
    cls: "t3",
    icon: "palace",
    duration: "Approximately 3–4 hours",
    groupType: "Up to 10 guests | Private Group",
    languages: "English, French, Arabic",
    price: "700 MAD",
    priceNote: "700 MAD per private group — up to 10 guests",
    description:
      "Journey through the rich history of Marrakesh, exploring iconic monuments, historic palaces, museums, and architectural treasures. Discover the dynasties, personalities, art, and traditions that shaped the Red City with a private official guide.",
    fullDescription: [
      "Journey through the rich history of Marrakesh, exploring iconic monuments, historic palaces, museums, and architectural treasures. Discover the dynasties, personalities, art, and traditions that shaped the Red City with a private official guide.",
      "Step into the history of Marrakesh through some of the city’s most remarkable monuments, museums and architectural treasures.",
      "From the iconic Koutoubia to the former palace of Dar El Bacha and the remarkable Ben Youssef Madrasa, discover the stories, dynasties and cultural heritage that shaped Marrakesh. Explore the architecture, art and history of these remarkable sites while learning about the dynasties and personalities that shaped the city.",
    ],
    highlights: [
      "Koutoubia Mosque",
      "Dar El Bacha Museum",
      "Ben Youssef Madrasa",
      "Marrakesh Museum",
      "Imperial Moorish and dynastic architecture",
      "Stories of sultans, scholars, and master craftsmen",
    ],
    gallery: [
      {
        src: "/images/bahia.jpg",
        alt: "Bahia Palace courtyard",
        caption: "Splendid Moorish tilework and courtyards of the imperial palaces.",
      },
      {
        src: "/images/medina.jpg",
        alt: "Ancient Medina walls",
        caption: "The ochre rammed-earth ramparts that have guarded Marrakesh for 900 years.",
      },
      {
        src: "/images/hero.jpg",
        alt: "Zaky with architectural detail",
        caption: "Zaky sharing historical context at historical sites.",
      },
      {
        src: "/images/souks.jpg",
        alt: "Artisan crafts in historic setting",
        caption: "Historic trade routes and guilds that enriched the imperial city.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Koutoubia Mosque",
        duration: "45 mins",
        description: "Explore the iconic 12th-century Almohad minaret, decorative sandstone bands, and surrounding historic gardens.",
        lat: 31.6238,
        lng: -7.9936,
      },
      {
        stopNumber: 2,
        name: "Dar El Bacha Museum",
        duration: "45 mins",
        description: "Step into the former palace of the Pasha of Marrakesh, admiring exquisite carved cedar ceilings, zellij tilework, and museum exhibits.",
        lat: 31.6318,
        lng: -7.9912,
      },
      {
        stopNumber: 3,
        name: "Ben Youssef Madrasa",
        duration: "45 mins",
        description: "Discover the remarkable 14th-century Islamic college with its stucco calligraphy, cedar balconies, and serene courtyard.",
        lat: 31.6320,
        lng: -7.9868,
      },
      {
        stopNumber: 4,
        name: "Marrakesh Museum",
        duration: "45 mins",
        description: "Explore the architecture, art and history of this 19th-century palace showcasing Moroccan pottery, jewelry, and weapons.",
        lat: 31.6315,
        lng: -7.9865,
      },
    ],
    mapCenter: { lat: 31.6280, lng: -7.9890, zoom: 15 },
    included: [
      "Private official tour guide",
      "Personalized guided visit",
      "Historical and cultural explanations",
      "Local insights and recommendations",
    ],
    notIncluded: [
      "Entrance fees",
      "Food and drinks",
      "Personal purchases",
      "Transportation",
    ],
  },
  {
    id: "tour-bynight",
    slug: "marrakesh-by-night",
    title: "Marrakesh By Night, Medina & Nightlife Experience",
    subtitle: "Discover the magic of Marrakesh after sunset",
    cls: "t4",
    icon: "tea",
    duration: "Approximately 2–3 hours",
    groupType: "Up to 10 guests | Private Group",
    languages: "English, French, Arabic",
    price: "1,000 MAD",
    priceNote: "1,000 MAD per private group — up to 10 guests",
    description:
      "Experience the magic of Marrakesh after sunset with an evening walk through the Medina, Jemaa el-Fna, and atmospheric souks. Discover local food, traditional cafés, illuminated landmarks, and hidden corners while enjoying personalized recommendations from your private local guide.",
    fullDescription: [
      "Experience the magic of Marrakesh after sunset with an evening walk through the Medina, Jemaa el-Fna, and atmospheric souks. Discover local food, traditional cafés, illuminated landmarks, and hidden corners while enjoying personalized recommendations from your private local guide.",
      "As the sun goes down, Marrakesh reveals another side of itself. Experience the energy of the Red City after dark, from the legendary Jemaa el-Fna to the atmospheric streets of the Medina.",
      "Enjoy a relaxed evening with a local guide, discover the city’s night-time traditions and let me help you choose the right place for dinner or an evening experience.",
    ],
    highlights: [
      "Evening walk through the Medina",
      "Jemaa el-Fna after sunset",
      "The illuminated Koutoubia and surrounding area",
      "Night atmosphere of the souks",
      "Local food and street-food scene",
      "Traditional cafés and hidden corners",
      "Recommendations for dinner and evening entertainment",
    ],
    gallery: [
      {
        src: "/images/medina.jpg",
        alt: "Medina at dusk",
        caption: "Atmospheric evening light reflecting on Medina walls and alleyways.",
      },
      {
        src: "/images/souks.jpg",
        alt: "Glowing lanterns in the night souks",
        caption: "Handcrafted brass lanterns illuminating the night souks.",
      },
      {
        src: "/images/hero.jpg",
        alt: "Zaky enjoying Marrakesh at night",
        caption: "Zaky guiding guests through vibrant evening traditions.",
      },
      {
        src: "/images/bahia.jpg",
        alt: "Traditional rooftop setting",
        caption: "Panoramic terraces overlooking the vibrant night skyline.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Illuminated Koutoubia & Surrounding Area",
        duration: "30 mins",
        description: "Begin with views of the illuminated Koutoubia minaret and surrounding gardens as twilight settles over the city.",
        lat: 31.6240,
        lng: -7.9935,
      },
      {
        stopNumber: 2,
        name: "Jemaa el-Fna After Sunset",
        duration: "45 mins",
        description: "Experience the vibrant energy of the world-famous square after dark: storytellers, musicians, and heritage food stalls.",
        lat: 31.6258,
        lng: -7.9891,
      },
      {
        stopNumber: 3,
        name: "Night Atmosphere of the Souks",
        duration: "30 mins",
        description: "Stroll along the atmospheric night souks where lantern shops glow and artisan workshops wind down for the evening.",
        lat: 31.6275,
        lng: -7.9880,
      },
      {
        stopNumber: 4,
        name: "Traditional Café & Rooftop Vantage Point",
        duration: "30 mins",
        description: "Savor spiced Moroccan tea or fresh juices at a traditional café while taking in views over the lively Medina streets.",
        lat: 31.6265,
        lng: -7.9875,
      },
      {
        stopNumber: 5,
        name: "Local Food Scene & Dinner Venue",
        duration: "30 mins",
        description: "Discover trusted local street food corners and receive personalized dinner recommendations and table reservations.",
        lat: 31.6260,
        lng: -7.9885,
      },
    ],
    mapCenter: { lat: 31.6260, lng: -7.9890, zoom: 16 },
    included: [
      "Private official tour guide",
      "Private evening walking experience",
      "Local stories and cultural insights",
      "Assistance with dinner arrangements",
      "Restaurant recommendations based on your preferences",
      "Assistance throughout the evening",
    ],
    notIncluded: [
      "Dinner and drinks",
      "Personal purchases",
      "Entrance fees, if applicable",
      "Private transportation",
      "Any additional entertainment or activities",
    ],
  },
  {
    id: "tour-signature-7days",
    slug: "marrakesh-private-signature-experience-7-days",
    title: "Marrakesh Private Signature Experience — 7 Days",
    subtitle: "6 Nights • Up to 6 Guests • Dedicated Guiding, Private Vehicle & Concierge",
    cls: "t5",
    icon: "monument",
    duration: "7 Days / 6 Nights",
    groupType: "Up to 6 Guests | Private Signature Journey",
    languages: "English, French, Arabic",
    price: "21,000 MAD",
    priceNote: "21,000 MAD for the complete 7-day private service (Up to 6 guests)",
    description:
      "Experience the best of Marrakesh and its surroundings with a fully private, personalized journey designed for up to six guests. From the historic Medina and Atlas Mountains to the Agafay Desert and Atlantic coast, enjoy dedicated guiding, private transportation, local expertise, and concierge assistance throughout your stay.",
    fullDescription: [
      "Experience the best of Marrakesh and its surroundings with a fully private, personalized journey designed for up to six guests. From the historic Medina and Atlas Mountains to the Agafay Desert and Atlantic coast, enjoy dedicated guiding, private transportation, local expertise, and concierge assistance throughout your stay.",
      "A complete private experience combining guiding, transportation, personal assistance and concierge service throughout your stay in Marrakesh.",
      "Your itinerary is designed to give you the freedom to discover Marrakesh, the Atlas Mountains, the Agafay Desert and the Atlantic coast, while having a dedicated local guide to assist you throughout your journey. Pricing: 21,000 MAD for up to 6 guests (Day 1: 1,750 MAD • Days 2–6: 3,500 MAD/day • Day 7: 1,750 MAD).",
    ],
    highlights: [
      "Day 1: Arrival & First Taste of Marrakesh (Airport pick-up, private Mercedes Vito, Jemaa el-Fna)",
      "Day 2: Discover Marrakesh (Ben Youssef Madrasa, Secret Garden, Medina & Souks)",
      "Day 3: Atlas Mountains & Imlil (Scenic High Atlas drive, Imlil valley, Kasbah Tamadot)",
      "Day 4: Majorelle Garden & Agafay Desert (Quad biking, sunset camel ride, desert dinner under stars)",
      "Day 5: Essaouira & the Atlantic Coast (Historic ramparts, Skala, fishing port, seaside lunch)",
      "Day 6: Your Choice of Experience (Hot-air balloon, cooking class, traditional hammam, 4x4)",
      "Day 7: Departure (Check-out assistance, private transfer to Marrakesh Airport)",
    ],
    gallery: [
      {
        src: "/images/hero.jpg",
        alt: "High Atlas Mountains and Moroccan landscapes",
        caption: "Spectacular excursions from the Atlas Mountains to the Agafay Desert.",
      },
      {
        src: "/images/medina.jpg",
        alt: "Marrakesh historic Medina",
        caption: "In-depth private discovery of imperial palaces and secret gardens.",
      },
      {
        src: "/images/bahia.jpg",
        alt: "Essaouira and coastal ramparts",
        caption: "Atlantic coastal breezes, historic fishing ports, and seaside dining.",
      },
      {
        src: "/images/souks.jpg",
        alt: "Private luxury transportation and guiding",
        caption: "Dedicated Mercedes Vito and personal concierge assistance all 7 days.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Day 1 — Arrival & First Taste of Marrakesh",
        duration: "Day 1",
        description: "Airport pick-up with private Mercedes Vito, hotel check-in assistance, orientation tour of Marrakesh, evening at Jemaa el-Fna, and dinner arrangements.",
        lat: 31.6069,
        lng: -8.0363,
      },
      {
        stopNumber: 2,
        name: "Day 2 — Discover Marrakesh Historic Heart",
        duration: "Day 2",
        description: "Full day exploring Ben Youssef Madrasa, The Secret Garden, Marrakesh Medina, traditional souks, Jemaa el-Fna, and Moroccan craftsmanship.",
        lat: 31.6320,
        lng: -7.9868,
      },
      {
        stopNumber: 3,
        name: "Day 3 — Atlas Mountains & Imlil Valley",
        duration: "Day 3",
        description: "Scenic High Atlas drive, visit Imlil and Berber villages, lunch at Kasbah Tamadot (or selected alternative), and return via Lalla Takerkoust.",
        lat: 31.1350,
        lng: -7.9190,
      },
      {
        stopNumber: 4,
        name: "Day 4 — Majorelle Garden & Agafay Desert",
        duration: "Day 4",
        description: "Morning at Majorelle Garden & European quarter. Afternoon transfer to Agafay for quad biking, sunset camel ride, desert dinner, and live music.",
        lat: 31.4285,
        lng: -8.1880,
      },
      {
        stopNumber: 5,
        name: "Day 5 — Essaouira & the Atlantic Coast",
        duration: "Day 5",
        description: "Private drive to Essaouira: guided Medina tour, Skala ramparts, working fishing port, lunch by the sea, and free time to explore.",
        lat: 31.5125,
        lng: -9.7700,
      },
      {
        stopNumber: 6,
        name: "Day 6 — Your Choice of Curated Experience",
        duration: "Day 6",
        description: "Flexible day: hot-air balloon sunrise flight, Moroccan cooking class, traditional hammam & spa, personal shopping, or 4x4 off-road adventure.",
        lat: 31.6288,
        lng: -7.9860,
      },
      {
        stopNumber: 7,
        name: "Day 7 — Departure & Airport Transfer",
        duration: "Day 7",
        description: "Hotel check-out assistance, private transfer to Marrakesh Airport, and dedicated assistance until departure.",
        lat: 31.6069,
        lng: -8.0363,
      },
    ],
    mapCenter: { lat: 31.6295, lng: -7.9810, zoom: 9 },
    included: [
      "Private official tour guide",
      "Private air-conditioned vehicle, generally a Mercedes Vito",
      "Service for up to 6 guests",
      "Airport transfers",
      "Guiding throughout the itinerary",
      "Personal assistance",
      "Concierge service",
      "Restaurant recommendations and dinner assistance",
      "Evening outings",
      "Transportation for the planned excursions",
      "Flexible itinerary and local recommendations",
    ],
    notIncluded: [
      "Hotel accommodation",
      "Entrance fees to monuments, museums and gardens",
      "Meals and drinks",
      "Quad biking",
      "Camel rides",
      "Hot-air balloon flights",
      "Boat trips",
      "Hammam and spa treatments",
      "Optional activities",
      "Personal purchases and expenses",
      "Any service not specifically mentioned as included",
    ],
  },
  {
    id: "tour-oualidia-5days",
    slug: "marrakesh-oualidia-coastal-escape-5-days",
    title: "Marrakesh & Oualidia Private Coastal Escape — 5 Days",
    subtitle: "4 Nights • Up to 6 Guests • Historic Medina, Safi Pottery & Atlantic Lagoon",
    cls: "t6",
    icon: "road",
    duration: "5 Days / 4 Nights",
    groupType: "Up to 6 Guests | Private Coastal Escape",
    languages: "English, French, Arabic",
    price: "14,000 MAD",
    priceNote: "14,000 MAD per private group (4 Nights • Up to 6 Guests)",
    description:
      "Journey from the vibrant streets of Marrakesh to the tranquil Atlantic coast of Oualidia on a private five-day escape. Discover Marrakesh's historic Medina, explore Safi's renowned pottery heritage, unwind beside Oualidia Lagoon, and experience the Portuguese heritage of El Jadida with private transportation, expert guiding, and personalized local assistance.",
    fullDescription: [
      "Journey from the vibrant streets of Marrakesh to the tranquil Atlantic coast of Oualidia on a private five-day escape. Discover Marrakesh's historic Medina, explore Safi's renowned pottery heritage, unwind beside Oualidia Lagoon, and experience the Portuguese heritage of El Jadida with private transportation, expert guiding, and personalized local assistance.",
      "A private journey from Marrakesh to the Atlantic coast. Discover the highlights of Marrakesh and experience the authentic Atlantic charm of Oualidia, with private transportation, personal guiding and assistance throughout your journey.",
      "Pricing: 14,000 MAD per private group, up to 6 guests. The first and last days are charged at 50% of the standard daily service rate, reflecting the shorter service time on arrival and departure days.",
    ],
    highlights: [
      "Day 1: Arrival & First Taste of Marrakesh (Airport pick-up, private Mercedes Vito, orientation walk)",
      "Day 2: Discover Marrakesh (Ben Youssef Madrasa, Secret Garden, Medina & Souks)",
      "Day 3: Marrakesh, Safi & Oualidia (Safi pottery quarter, ceramic crafts, Atlantic coast relaxation)",
      "Day 4: Oualidia Lagoon & El Jadida (Lagoon boat ride, Portuguese cistern and fortified ramparts)",
      "Day 5: Departure (Check-out assistance, private transfer to airport)",
      "Optional Oualidia Experiences (Private lagoon boat ride ~500 MAD, Beach picnic ~700 MAD/person)",
    ],
    gallery: [
      {
        src: "/images/bahia.jpg",
        alt: "Oualidia coastal lagoon and waters",
        caption: "The peaceful turquoise lagoon and pristine oyster beds of Oualidia.",
      },
      {
        src: "/images/medina.jpg",
        alt: "Marrakesh Medina streets",
        caption: "Historic streets and vibrant artisan quarters in Marrakesh.",
      },
      {
        src: "/images/souks.jpg",
        alt: "Safi ceramics and pottery",
        caption: "Centuries-old pottery traditions in the coastal ceramic city of Safi.",
      },
      {
        src: "/images/hero.jpg",
        alt: "Zaky with guests on coastal tour",
        caption: "Dedicated guiding and private Mercedes Vito throughout Morocco.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Day 1 — Arrival & First Taste of Marrakesh",
        duration: "Day 1",
        description: "Airport pick-up in private air-conditioned vehicle, hotel check-in assistance, orientation walk, and evening around Jemaa el-Fna.",
        lat: 31.6069,
        lng: -8.0363,
      },
      {
        stopNumber: 2,
        name: "Day 2 — Discover Marrakesh",
        duration: "Day 2",
        description: "Ben Youssef Madrasa, The Secret Garden, Marrakesh Medina, traditional souks, Jemaa el-Fna Square, and local craftsmanship.",
        lat: 31.6320,
        lng: -7.9868,
      },
      {
        stopNumber: 3,
        name: "Day 3 — Marrakesh, Safi & Oualidia",
        duration: "Day 3",
        description: "Private departure to Safi's famous pottery quarter, discover traditional ceramic craftsmanship, continue to Oualidia, check-in, and seaside lunch.",
        lat: 32.2994,
        lng: -9.2372,
      },
      {
        stopNumber: 4,
        name: "Day 4 — Oualidia Lagoon & El Jadida",
        duration: "Day 4",
        description: "Explore the beautiful lagoon, optional private boat ride, continue to El Jadida to tour the UNESCO Portuguese city, and return to Marrakesh.",
        lat: 32.7330,
        lng: -9.0435,
      },
      {
        stopNumber: 5,
        name: "Day 5 — Departure & Airport Transfer",
        duration: "Day 5",
        description: "Check-out assistance, private transfer to the airport, and dedicated assistance until departure.",
        lat: 31.6069,
        lng: -8.0363,
      },
    ],
    mapCenter: { lat: 32.3000, lng: -8.8000, zoom: 8 },
    included: [
      "Private official Moroccan tour guide",
      "Private air-conditioned vehicle, generally a Mercedes Vito",
      "Up to 6 guests",
      "Airport transfers",
      "Private transportation throughout the itinerary",
      "Marrakesh–Safi–Oualidia–El Jadida–Marrakesh journey",
      "Professional guiding throughout the experience",
      "Personal assistance",
      "Concierge service",
      "Restaurant recommendations and assistance",
      "Flexible itinerary and local recommendations",
    ],
    notIncluded: [
      "Hotel accommodation",
      "Meals and drinks",
      "Entrance fees",
      "Optional Oualidia boat ride (approx. 500 MAD per boat)",
      "Beach picnic (approx. 700 MAD per person)",
      "Optional activities",
      "Personal purchases and expenses",
      "Any service not specifically mentioned above",
    ],
  },
  {
    id: "tour-custom",
    slug: "customized-private-tours",
    title: "Customized Private Tours",
    subtitle: "Tailored to your interests, pace, and preferences with private guiding",
    cls: "t7",
    icon: "compass",
    duration: "Flexible (Half, Full or Multi-Day)",
    groupType: "Tailored to your party | Private Experience",
    languages: "English, French, Arabic",
    price: "Custom Quote",
    priceNote: "Tailored to your party size, duration, and preferences",
    description:
      "Create your perfect Moroccan experience with a fully customized private tour designed around your interests, pace, and preferences. Whether you want to explore Marrakesh's heritage, discover local markets and cuisine, escape to the Atlas Mountains, or venture beyond the city, your itinerary is tailored to you with private guiding, transportation, and personalized local assistance.",
    fullDescription: [
      "Create your perfect Moroccan experience with a fully customized private tour designed around your interests, pace, and preferences. Whether you want to explore Marrakesh's heritage, discover local markets and cuisine, escape to the Atlas Mountains, or venture beyond the city, your itinerary is tailored to you with private guiding, transportation, and personalized local assistance.",
      "Tell Zaky what interests you most — from hidden architecture and artisan workshops to culinary immersions and multi-day country excursions. Every hour is shaped to deliver an authentic, stress-free, and memorable journey.",
      "Enjoy private door-to-door coordination, flexible departure times, and insider access to places standard group tours never reach.",
    ],
    highlights: [
      "100% tailor-made itinerary crafted around your specific wishlist and pace",
      "Ideal for families, photographers, couples, and specialized collectors",
      "Flexible starting time and hotel/riad pickup anywhere in central Marrakesh",
      "Combine elements of Medina heritage, souks, cuisine, and nature escapes",
      "Direct personal consultation with Zaky before and during your journey",
      "Options for private Mercedes Vito transportation throughout Morocco",
    ],
    gallery: [
      {
        src: "/images/hero.jpg",
        alt: "Customized Marrakesh tour with Zaky",
        caption: "Private excursions tailored around what you love most.",
      },
      {
        src: "/images/medina.jpg",
        alt: "Private Medina exploration",
        caption: "Discreet alleys and serene courtyards away from crowded routes.",
      },
      {
        src: "/images/bahia.jpg",
        alt: "Architectural wonders",
        caption: "Dedicated time for photography and architectural appreciation.",
      },
      {
        src: "/images/souks.jpg",
        alt: "Curated shopping and artisan meetings",
        caption: "Meet specific master artisans matching your design interests.",
      },
    ],
    itinerary: [
      {
        stopNumber: 1,
        name: "Personal Consultation & Hotel Briefing",
        duration: "Flexible",
        description: "Meet Zaky at your hotel or riad to finalize your personalized daily route over Moroccan coffee or tea.",
        lat: 31.6258,
        lng: -7.9891,
      },
      {
        stopNumber: 2,
        name: "Tailored Priority Discoveries",
        duration: "Flexible",
        description: "Explore your curated interests: hidden art galleries, ancient medersas, garden sanctuaries, or private craft guilds.",
        lat: 31.6310,
        lng: -7.9870,
      },
      {
        stopNumber: 3,
        name: "Handpicked Authentic Dining",
        duration: "Flexible",
        description: "Enjoy dining reservations at authentic riads, mountain terraces, or seaside bistros matching your preferences.",
        lat: 31.6270,
        lng: -7.9850,
      },
      {
        stopNumber: 4,
        name: "Bespoke Afternoon Excursions",
        duration: "Flexible",
        description: "Dedicated artisan meetings, specialized shopping requests, photography golden hour, or scenic countryside drives.",
        lat: 31.6295,
        lng: -7.9880,
      },
    ],
    mapCenter: { lat: 31.6280, lng: -7.9880, zoom: 15 },
    included: [
      "Licensed guide services exclusively for your private party (Zaky)",
      "Pre-trip consultation via WhatsApp or email to craft your itinerary",
      "Hotel or riad pickup in central Marrakesh",
      "Total flexibility during the tour",
      "Local insights, artisan access, and concierge assistance",
    ],
    notIncluded: [
      "Monument admission tickets",
      "Meals and drinks",
      "Optional vehicle transport (arranged upon request)",
      "Gratuities",
    ],
  },
];
